[global]
# see https://gitlab.com/riseproject/python/wheel_builder
index-url = https://gitlab.com/api/v4/projects/56254198/packages/pypi/simple
extra-index-url =
    https://pypi.org/simple
    https://pypi.tuna.tsinghua.edu.cn/simple