name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [
            {
              image: ubuntu:22.04,
              container-exec: "docker exec u22",
              container-name: "u22",
            },
            # {
            #   image: ubuntu:24.04,
            #   container-exec: "docker exec u24",
            #   container-name: "u24",
            # },
            # {
            #   image: debian:13,
            #   container-exec: "docker exec deb13",
            #   container-name: "deb13",
            # },
          ]
    steps:
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64

      - name: setup docker  Buildx
        uses: docker/setup-buildx-action@v3

      - name: start container
        run: |
          docker run --platform linux/riscv64 -d --name  ${{matrix.container.container-name}} -v ./:/src ${{matrix.container.image}} bash -c "while true; do sleep 30; done"

      - name: Show uname info
        run: |
          ${{matrix.container.container-exec}} uname -a
          ${{matrix.container.container-exec}} cat /etc/os-release

      - name: install tool
        run: |
          ${{matrix.container.container-exec}} bash -c "apt update && apt install wget unzip -y"
          ${{matrix.container.container-exec}} cat /etc/os-release

      - name: predownload ceph-boost
        run: |
          ${{matrix.container.container-exec}} bash -c "wget https://github.com/ffgan/ceph-boost-riscv/releases/download/u22%2Bu24/ceph-boost-deb-u22.zip"
          ${{matrix.container.container-exec}} bash -c "unzip ceph-boost-deb-u22.zip && unzip ceph-boost-all.zip"

      - name: predownload valgrind 3.25.1
        run: |
          ${{matrix.container.container-exec}} bash -c "wget https://github.com/ffgan/valgrind-riscv-deb/releases/download/0.0.1/valgrind-deb.zip"
          ${{matrix.container.container-exec}} bash -c "unzip valgrind-deb.zip"

      - name: exec install
        run: |
          ${{matrix.container.container-exec}} bash -c "apt install --fix-broken -y ./*deb"

      # - name: exec ./install-deps.sh
      #   run: |
      #     ${{matrix.container.container-exec}} bash -c "wget https://answers.launchpad.net/ubuntu/+archive/primary/+sourcefiles/valgrind/1:3.25.1-0ubuntu1/valgrind_3.25.1-0ubuntu1.debian.tar.xz && tar -xf valgrind_3.25.1-0ubuntu1.debian.tar.xz && cd debian && ls -l "
