name: ceph install deps

on:
  push:
  workflow_dispatch:

jobs:
  fedora_riscv_install_deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container:
          [
            {
              image: fedorariscv/base:41,
              container-exec: "docker exec fedora",
              container-name: "fedora",
            },
            {
              image: fedorariscv/base:42,
              container-exec: "docker exec fedora",
              container-name: "fedora",
            },
            {
              image: fedorariscv/base:43,
              container-exec: "docker exec fedora",
              container-name: "fedora",
            },
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: fedora
          sparse-checkout: |
            openblas.pc
            pip.conf
          sparse-checkout-cone-mode: false
          path: openblas
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          repository: ffgan/ceph
          ref: rv64-pypi
          fetch-depth: 1
          path: ceph

      - name: setup qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64

      - name: setup docker  Buildx
        uses: docker/setup-buildx-action@v3

      - name: start container
        run: |
          docker run --platform linux/riscv64 -d --name ${{matrix.container.container-name}} -v ./ceph:/src ${{matrix.container.image}} sleep infinity

      - name: Show uname info and os-release
        run: |
          ${{matrix.container.container-exec}} uname -a
          ${{matrix.container.container-exec}} cat /etc/os-release

      - name: install builddep
        run: |
          ${{matrix.container.container-exec}} bash -c "dnf update -y && dnf5 install -y 'dnf5-command(builddep)' wget unzip rust cargo openssl-devel libffi-devel gcc gcc-gfortran openblas-devel"

      - name: conf pip source
        run: |
          ${{matrix.container.container-exec}} bash -c "mkdir ~/.pip"
          docker cp openblas/pip.conf fedora:/root/.pip/pip.conf

      # in order to build scipy (under riscv64)
      - name: copy openblas to container
        run: |
          docker cp openblas/openblas.pc fedora:/usr/lib64/pkgconfig/openblas.pc

      - name: install missing rpm
        if: ${{ matrix.container.image != "fedorariscv/base:41" }}
        run: |
          ${{matrix.container.container-exec}} bash -c "wget https://github.com/ffgan/ceph-riscv/releases/download/0.0.1/ceph-fedora41-missing-rpm.zip && unzip ceph-fedora41-missing-rpm.zip && dnf install -y ./*.rpm"

      - name: exec ./install-deps.sh
        run: |
          ${{matrix.container.container-exec}} bash -c "cd /src && FOR_MAKE_CHECK=true ./install-deps.sh"

      - name: clean container
        if: always()
        run: |
          docker stop ${{matrix.container.container-name}}
          docker rm ${{matrix.container.container-name}}
