name: ceph install deps

on:
  push:

jobs:
  fedora_riscv_install_deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [
            {
              image: fedorariscv/base:latest,
              container-exec: "docker exec fedora",
              container-name: "fedora",
            },
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          repository: ffgan/ceph
          ref: rv64-install-deps
          fetch-depth: 1

      - name: setup qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64

      - name: setup docker  Buildx
        uses: docker/setup-buildx-action@v3

      - name: start container
        run: |
          docker run --platform linux/riscv64 -d --name  ${{matrix.container.container-name}} -v ./:/src ${{matrix.container.image}} sleep infinity

      - name: Show uname info and os-release
        run: |
          ${{matrix.container.container-exec}} uname -a
          ${{matrix.container.container-exec}} cat /etc/os-release

      - name: install builddep
        run: |
          ${{matrix.container.container-exec}} bash -c "dnf update -y && dnf5 install -y 'dnf5-command(builddep)'"

      - name: exec ./install-deps.sh
        run: |
          ${{matrix.container.container-exec}} bash -c "cd /src && FOR_MAKE_CHECK=true ./install-deps.sh"

      - name: clean container
        if: always()
        run: |
          docker stop ${{matrix.container.container-name}}
          docker rm ${{matrix.container.container-name}}
