name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build_and_test_ceph:
    runs-on: self-hosted
    timeout-minutes: 30000
    steps:
      - name: Show uname info
        run: |
          ssh rvu24 "uname -a;cat /etc/os-release"

      - name: Download source code
        run: |
          ssh rvu24 "mkdir -p ceph && cd ceph && git clone --depth 1 --branch daily/jinzhu https://code.risc-vers.cn/risc-verse/wg-cloudcomputing/ceph-riscv.git"

      - name: init submoudlue
        run: |
          ssh rvu24 "cd ceph && git submodule update --init --recursive"

      - name: install dep
        run: |
          ssh rvu24 "cd ceph && ls -l && ./install-deps.sh && git config --global safe.directory '*'"

      - name: do_cmake
        run: |
          ssh rvu24 "cd ceph && export NPM_REGISTRY=https://mirrors.cloud.tencent.com/npm/ && export  NODE_OPTIONS=--max-old-space-size=8192 && rm -rf build && ./do_cmake.sh"

      - name: ninja build
        run: |
          ssh rvu24 "cd ceph/build && export NPM_REGISTRY=https://mirrors.cloud.tencent.com/npm/ && export  NODE_OPTIONS=--max-old-space-size=8192 && cmake -DWITH_MGR_DASHBOARD_FRONTEND=OFF .. && ninja -j64 -k0"

      - name: ninja check
        run: |
          ssh rvu24 "cd ceph/build && ninja check -j64 -k0"