name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    runs-on: self-hosted
    timeout-minutes: 30000
    steps:
      - name: Show uname info
        run: |
          ssh rv_u24 "uname -a;cat /etc/os-release"

      - name: init submoudlue
        run: |
          ssh rv_u24 "cd /src && git submodule update --init --recursive"

      - name: install dep
        run: |
          ssh rv_u24 "cd /src && ls -l && FOR_MAKE_CHECK=true ./install-deps.sh"

      - name: do_cmake
        run: |
          ssh rv_u24 "cd /src && rm -rf build ; rm -rf ./dist;./do_cmake.sh"

      - name: ninja build
        run: |
          ssh rv_u24 "cd /src/build && ninja -j64 -k0"

      - name: ninja check
        run: |
          ssh rv_u24 "cd /src/build && ninja check -j64 -k0"