name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    runs-on: self-hosted
    timeout-minutes: 30000
    steps:
      - name: Show uname info
        run: |
          ssh rvu24 "uname -a;cat /etc/os-release"

      - name: init submoudlue
        run: |
          ssh rvu24 "cd /src && git pull --rebase &&git submodule update --init --recursive"

      - name: install dep
        run: |
          ssh rvu24 "cd /src && ls -l && FOR_MAKE_CHECK=true ./install-deps.sh && git config --global safe.directory '*'"

      - name: do_cmake
        run: |
          ssh rvu24 "cd /src && NPM_REGISTRY="https://mirrors.cloud.tencent.com/npm/" NODE_OPTIONS="--max-old-space-size=8192" ./do_cmake.sh"

      - name: ninja build
        run: |
          ssh rvu24 "cd /src/build && cmake -DWITH_MGR_DASHBOARD_FRONTEND=OFF .. && ninja -j64 -k0"

      - name: ninja check
        run: |
          ssh rvu24 "cd /src/build && ninja check -j64 -k0"